#! /usr/bin/python3

import requests 
import json
import base64
import os

def get_token():
	client_id = 'rTD5KIe8AnN7rUy7O1nCpqto'
	client_secret = 'ZfrkZKt5fTqLh9e17OknYQk7QxuuBEpR'
	host = 'https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials&client_id=%s&client_secret=%s'%(client_id,client_secret)
	response = requests.get(host)
	if response:
		data = response.json()
		return data['access_token']
	else:
		return "Can't get access_token"
		
		
def imgdata(filepath):
	with open(filepath, 'rb') as f:
		image = f.read()
		image_base64 = str(base64.b64encode(image), encoding='utf-8')
		f.close()
		os.remove('./1.jpeg');
		return image_base64


while(1):
	while os.path.exists('./1.jpeg'):
		request_url = "https://aip.baidubce.com/rest/2.0/face/v3/search"
		image64 = imgdata('./1.jpeg')
		params = {
				'image': image64,
				'image_type': 'BASE64',
				'group_id_list': 'group1',
				'quality_control': 'LOW',
				'liveness_control': 'LOW'
				}
		params = json.dumps(params)
		access_token = get_token()
		request_url = request_url + "?access_token=" + access_token
		headers = {'content-type': 'application/json'}
		response = requests.post(request_url, data=params, headers=headers)
		if response:
			data = response.json()	
			score = data['result']['user_list'][0]['score']
			user_info = data['result']['user_list'][0]['user_info']
			if score > 80:
				result = {'result': 1,'user_info': user_info}
				with open('./result.json',"w") as f:
					json.dump(result, f)
				f.close()
				print("识别成功，欢迎 %s" % user_info)
			else:
				result = {'result': 0}
				with open('./result.json',"w") as f:
					json.dump(result, f)
				f.close()
				print("识别失败，无此用户")
		else:
			print("Error!")
